global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Fraud Detection Service
  - job_name: 'fraud-detection'
    static_configs:
      - targets: ['fraud-detection:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
    # Add custom labels
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.+)'
        replacement: 'fraud-detection-service'
      
      - source_labels: [__address__]
        target_label: service
        regex: '(.+)'
        replacement: 'fraud-detection'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
